[project]
name = "mau"
version = "3.2.0"
description = "Mau card game engine. Play Mau with your friends."
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "AGPL-3.0-or-later"
dependencies = [
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "nox>=2025.2.9",
    "pyright>=1.1.414",
    "ruff>=0.16.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.12",
    "mkdocstrings>=1.0.6",
    "mkdocstrings-python>=1.16.10",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.mypy]
ignore_errors = true # I use pyright only because mypy dumb

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportPrivateUsage = false
reportMissingTypeStubs = true
reportUnnecessaryTypeIgnoreComment = "warning"
reportUninitializedInstanceVariable = "error"
