name: Mau web check
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
    - name: Set up Bun.js
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install
      working-directory: mau-web
    - name: Lint project
      run: bun lint
      working-directory: mau-web
    - name: Type check
      run: bun type-check
      working-directory: mau-web

